### ISSUE TITLE
Error after file conversion

### ISSUE THREAD

**Issue by blindibrasil** [zxhaaa6/awesome-unoconv#2]
How to resolve this error after file conversion?

```
Error: func=xmlSecCheckVersionExt:file=xmlsec.c:line=188:obj=unknown:subj=unknown:error=19:invalid version:mode=abi compatible;expected minor version=2;real minor version=2;expected subminor version=25;real subminor version=26

    at ChildProcess.<anonymous> (/home/blindi/www/blindi/doctest/node_modules/awesome-unoconv/dist/converter.js:147:23)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

**Comment by zxhaaa6** [comment]
Should make sure your LibreOffice version is 4.2.5

**Comment by blindibrasil** [comment]
I had corrected it by doing the following:
In line 145 - awesome-unoconv/dist/converter.js
```
unoconv.on('close', function (code) {
      if (stderr.length === 0) {
        return reject(new Error(Buffer.concat(stderr).toString('utf8')));
      }
      
      resolve(option.output);
    });```
